// Built-in service and project content, used when WordPress has none.
import type { ServiceDetail, WorkDetail } from '@/lib/cms';

export const fallbackServiceDetails: ServiceDetail[] = [
  { slug: 'webdesign', title: 'Web', titleEm: 'Design', badge: 'Design & Interface', num: '01', tagline: 'Websites designed around your customers and your goals — clear, credible and built to turn visitors into enquiries.' },
  { slug: 'ui', title: 'UI/UX', titleEm: 'Design', badge: 'Design & Interface', num: '02', tagline: 'Interfaces people understand at a glance — research-backed UX and polished UI for web apps, software and mobile products.' },
  { slug: 'branding', title: 'Branding', titleEm: '& Identity', badge: 'Design & Identity', num: '03', tagline: 'A brand identity that stays consistent everywhere your customers meet you — from your website and software to print and social.' },
  { slug: 'logo', title: 'Logo', titleEm: 'Design', badge: 'Design & Identity', num: '04', tagline: 'Distinctive, versatile logos that look sharp at any size — on a phone screen, a storefront or a business card.' },
  { slug: 'responsive', title: 'Responsive', titleEm: 'Web Design', badge: 'Design & Interface', num: '05', tagline: 'Websites and web apps that adapt perfectly to every screen — phone, tablet, laptop and everything in between.' },
  { slug: 'webdev', title: 'Custom Software', titleEm: '& Web Apps', badge: 'Engineering', num: '06', tagline: 'Bespoke web applications, portals, dashboards and APIs built around how your business works — secure, scalable and easy to maintain.' },
  { slug: 'mobile', title: 'Mobile App', titleEm: 'Development', badge: 'Engineering', num: '07', tagline: 'iOS and Android apps that feel fast and natural — designed, built and launched from one cross-platform codebase.' },
  { slug: 'ecommerce', title: 'E-Commerce', titleEm: 'Development', badge: 'Engineering', num: '08', tagline: 'Online stores that look premium, load fast and make buying easy — on Shopify, WooCommerce or a fully custom platform.' },
  { slug: 'seo', title: 'SEO &', titleEm: 'Performance', badge: 'Growth', num: '09', tagline: 'Get found by the right customers on Google — technical SEO, on-page optimisation, local search and fast-loading pages.' },
  { slug: 'corporate', title: 'Corporate', titleEm: 'Websites', badge: 'Enterprise', num: '10', tagline: 'Professional, high-trust websites for established organisations — clear structure, strong governance and easy content management.' },
];

export const fallbackWorkDetails: WorkDetail[] = [
  {
    slug: 'grab-a-rental-car',
    titleHtml: 'Grab A<br><i>Rental Car</i>',
    shortName: 'Grab A Rental Car',
    tag: 'Car Rental · Booking Platform',
    num: '01 / 11',
    tagline: 'A complete online booking platform for an Auckland car rental company — vehicle listings, online quotes and bookings, secure Stripe payments and a custom dashboard for running the fleet.',
    client: 'Grab A Rental Car',
    year: '2025',
    duration: '',
    role: 'Design, Development & SEO',
    industry: 'Car Rental · Travel',
    tags: ['WordPress', 'Custom Theme', 'WooCommerce', 'Stripe', 'Advanced Custom Fields', 'Contact Form 7', 'OTP Verification', 'All in One SEO'],
    metrics: ['25', 'Online', 'Custom', 'NZD'],
    mLabels: ['Vehicles Listed', 'Quotes & Bookings', 'Operations Dashboard', 'Stripe Payments'],
    mChanges: ['Full fleet with specs & rates', '4-step online booking', 'Fleet, pick-ups & returns', 'Secure card checkout'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://grabarentalcar.co.nz',
    overviewHeading: ['Putting a whole rental ', 'fleet', ' online'],
    overview: [
      'Grab A Rental Car is an Auckland car rental company helping visitors and locals explore New Zealand their way. They needed a website that showed their full fleet and let customers get a quote, book and pay online — without picking up the phone.',
      'We designed and built a custom WordPress theme around their brand. Customers search by pick-up and drop-off location, date and time, compare every vehicle with its seats, fuel economy and daily rate, then book through a four-step flow — insurance, extras, driver details and payment — with a live booking summary, saved quotes and secure Stripe payments in NZD.',
      'Behind the scenes, we built a custom operations dashboard so the team can manage bookings, saved quotes and vehicles, and see the whole fleet at a glance — what is available, on rent, in service or being cleaned, plus pick-ups and returns due today and tomorrow. Phone-verified enquiry forms and SEO foundations help customers find and trust them online.',
    ],
    showcase: [
      { label: 'Home & Search', text: 'Brand-led home page with instant pick-up and drop-off search', image: '/work/grab-a-rental-car/home.webp' },
      { label: 'Vehicle Listings', text: 'Every car with seats, fuel economy, specs and daily rate', image: '/work/grab-a-rental-car/vehicles.webp' },
      { label: 'Booking Flow', text: 'Insurance, extras, details and payment with a live summary', image: '/work/grab-a-rental-car/booking-extras.webp' },
      { label: 'Operations Dashboard', text: 'Fleet status, bookings, pick-ups and returns at a glance', image: '/work/grab-a-rental-car/dashboard.webp' },
    ],
  },
  {
    slug: 'event-display',
    titleHtml: 'Event<br><i>Display</i>',
    shortName: 'Event Display',
    tag: 'LED Screen Hire · WooCommerce',
    num: '02 / 11',
    tagline: 'A rental and quoting website for a New Zealand LED screen hire company — choose a display by size, pick your rental dates and times, and request a quote online.',
    client: 'Event Display NZ',
    year: '2026',
    duration: '',
    role: 'Design, Development & SEO',
    industry: 'Event Hire · LED Screens',
    tags: ['WordPress', 'Custom Theme', 'Tailwind CSS', 'WooCommerce', 'Rental Date Picker', 'Quote Requests', 'Contact Form 7', 'Yoast SEO'],
    metrics: ['9', '1–6m', '8', '5-step'],
    mLabels: ['LED Displays', 'Screen Widths', 'Event Types', 'Rental Process'],
    mChanges: ['Small, double-sided & big screen', 'Choose the right wall size', 'Trade shows to weddings', 'From order to pickup'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://eventdisplay.co.nz',
    overviewHeading: ['Booking LED screens, ', 'made simple'],
    overview: [
      'Event Display hires out high-resolution LED screens and video walls for trade shows, corporate events, festivals, weddings and more across New Zealand. They needed a website that helped customers choose the right screen and send a complete rental request, instead of going back and forth by email.',
      'We built a custom WordPress and WooCommerce theme with Tailwind CSS. Customers browse nine LED displays across small, double-sided and big-screen ranges, filter by type or choose by wall width from 1 to 6 metres, then pick their rental dates and times on the product page and request a custom quote in one step.',
      'A bold home page slider shows the screens in action, and every product page explains the five-step process from order to pickup. The site also covers eight event types with past event videos and a video production add-on, and the contact form captures the business, location, product and rental dates up front — with Yoast SEO helping them rank for LED screen hire searches.',
    ],
    showcase: [
      { label: 'Home Page', text: 'Hero slider showing LED displays in action', image: '/work/event-display/home.webp' },
      { label: 'Shop', text: 'Nine LED displays with filters by screen type', image: '/work/event-display/shop.webp' },
      { label: 'Product & Quote', text: 'Pick rental dates and times, then request a quote', image: '/work/event-display/product.webp' },
      { label: 'Contact', text: 'Rental enquiry form with product and dates', image: '/work/event-display/contact.webp' },
    ],
  },
  {
    slug: 'baby-cart',
    titleHtml: 'Baby<br><i>Cart</i>',
    shortName: 'Baby Cart',
    tag: 'E-Commerce · WooCommerce',
    num: '03 / 11',
    tagline: 'A full-featured online store for New Zealand families — strollers, car seats and baby gear, with flexible payments, NZ-wide delivery and a custom store management dashboard.',
    client: 'Baby Cart NZ',
    year: '2026',
    duration: '',
    role: 'Design, Development & SEO',
    industry: 'Retail · Baby Products',
    tags: ['WordPress', 'Custom Theme', 'WooCommerce', 'Stripe & Apple Pay', 'Afterpay', 'GoSweetSpot Shipping', 'Yoast SEO Premium', 'Google & Facebook Shopping'],
    metrics: ['100+', 'Afterpay', 'NZ-wide', 'Custom'],
    mLabels: ['Products Online', 'Buy Now, Pay Later', 'Delivery & Click & Collect', 'Management Dashboard'],
    mChanges: ['Across 10+ categories', 'Plus Stripe & Apple Pay', 'Courier shipping options', 'Orders, products & customers'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://babycart.co.nz',
    overviewHeading: ['A trusted store for ', 'growing', ' families'],
    overview: [
      'Baby Cart is a New Zealand online store selling safe, stylish and certified baby gear — from convertible strollers and bassinets to car seats. Parents buying these products want confidence, clear information and an easy checkout.',
      'We designed and built a custom WooCommerce store organised into clear categories — strollers, car seats, bassinets, highchairs and more — with product search, colour options, image galleries, add-on products, wishlists and a rewards programme. Checkout supports Stripe, Apple Pay and Afterpay, with courier delivery and click & collect across New Zealand.',
      'To help the store grow, we added a sign-up discount, a waitlist for upcoming stock, advanced SEO with Yoast and Google and Facebook shopping feeds — and built a custom management dashboard where the team can track the order pipeline and manage products, customers, waitlist sign-ups and newsletter subscribers in one place.',
    ],
    showcase: [
      { label: 'Home Page', text: 'Seasonal promotions and new arrivals front and centre', image: '/work/baby-cart/home.webp' },
      { label: 'Shop & Categories', text: 'Browse 100+ products by category, with filters and sorting', image: '/work/baby-cart/shop.webp' },
      { label: 'Product Page', text: 'Colour options, add-ons, Afterpay and Apple Pay', image: '/work/baby-cart/product.webp' },
      { label: 'Management Dashboard', text: 'Order pipeline, products, customers and subscribers', image: '/work/baby-cart/dashboard.webp' },
    ],
  },
  {
    slug: 'bworth',
    titleHtml: 'Bworth<br><i>Outdoor Living</i>',
    shortName: 'Bworth',
    tag: 'Outdoor Living · Product Showcase',
    num: '04 / 11',
    tagline: 'A product showcase and lead-generation website for a New Zealand outdoor living company — louvre roofs, pergolas, blinds and more, with a product comparison tool and free onsite quote requests.',
    client: 'Bworth',
    year: '2025',
    duration: '',
    role: 'Design, Development & SEO',
    industry: 'Building · Outdoor Living',
    tags: ['WordPress', 'Custom Theme', 'Tailwind CSS', 'WooCommerce', 'ACF Pro', 'All in One SEO', 'Image Optimisation', 'Facebook Catalogue'],
    metrics: ['18', '11', 'Compare', 'Free'],
    mLabels: ['Products Online', 'Product Categories', 'Comparison Tool', 'Onsite Quotes'],
    mChanges: ['Including 8 louvre models', 'Louvres to fencing', 'Up to 3 systems side by side', 'Branches across NZ'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://bworth.co.nz',
    overviewHeading: ['Showcasing ', 'outdoor living', ' across NZ'],
    overview: [
      'Bworth designs and installs outdoor living solutions across New Zealand — louvre roofs, pergolas, outdoor blinds, awnings, carports, sunrooms and more. Their products are considered purchases, so the website needed to explain each system clearly and turn interest into onsite quote requests.',
      'We designed and built a custom WordPress theme with Tailwind CSS. A full-width hero slider introduces each product range, and an outdoor collection with category filters organises 18 products into 11 categories. Every product page lets customers choose the type, size and colour, alongside a gallery, specifications, optional add-ons, FAQs and a step-by-step installation process.',
      'To help customers choose, we built a comparison tool that lines up to three louvre systems side by side — control options, motor, app control, rain sensor and more. Free onsite quote requests are built into every page, with branch details across New Zealand, image optimisation for fast loading and SEO foundations to help Bworth rank for outdoor living searches.',
    ],
    showcase: [
      { label: 'Home Page', text: 'Hero slider for each product range, with free quote calls to action', image: '/work/bworth/home.webp' },
      { label: 'Product Collection', text: '18 products across 11 categories, with filters', image: '/work/bworth/products.webp' },
      { label: 'Comparison Tool', text: 'Up to three louvre systems compared side by side', image: '/work/bworth/compare.webp' },
      { label: 'Product Detail', text: 'Choose type, size and colour, with gallery and warranty highlights', image: '/work/bworth/product.webp' },
    ],
  },
  {
    slug: 'brand-alchemy',
    titleHtml: 'Brand<br><i>Alchemy</i>',
    shortName: 'Brand Alchemy',
    tag: 'Creative Agency · Next.js',
    num: '05 / 11',
    tagline: 'A bold, motion-led website for a New Zealand creative and brand agency — video storytelling, animated typography and clear service and industry pages, built with Next.js.',
    client: 'Brand Alchemy',
    year: '2025',
    duration: '',
    role: 'Website Development',
    industry: 'Creative & Brand Agency',
    tags: ['Next.js', 'React', '3D Video Hero', 'Scroll Animation', 'Animated Typography', 'Hover Previews', 'Responsive Design', 'Technical SEO'],
    metrics: ['7', '9', 'Next.js', 'Motion'],
    mLabels: ['Service Areas', 'Industries', 'Framework', 'Storytelling'],
    mChanges: ['Branding to software', 'Beauty to manufacturing', 'Fast, SEO-friendly pages', '3D hero & animated type'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://brandalchemy.co.nz',
    overviewHeading: ['Creativity, ', 'in code'],
    overview: [
      'Brand Alchemy is a New Zealand creative agency covering branding, marketing, advertising, print, video and software. As a creative business, their own website had to prove what they could do — bold, memorable and unmistakably on-brand.',
      'We built the site with Next.js and React, bringing their identity to life with a full-screen animated 3D hero behind oversized "Own Your Identity." typography, letter-by-letter text animation and scroll-driven sections that walk visitors through the Brand Alchemy story.',
      'Behind the creative layer, the site is fast, responsive and structured for search. Each service area pairs its full list of services with video, the industries page reveals example work as visitors move through the list, and a blog, careers and contact page help the team grow. Brand Alchemy is also our creative partner.',
    ],
    showcase: [
      { label: 'Home Hero', text: 'Animated 3D hero with oversized "Own Your Identity." typography', image: '/work/brand-alchemy/home.webp' },
      { label: 'Services', text: 'Each service area with its full service list and video', image: '/work/brand-alchemy/services.webp' },
      { label: 'Industries', text: 'Nine industries, with example work revealed on hover', image: '/work/brand-alchemy/industries.webp' },
      { label: 'Contact', text: 'A clean, simple enquiry form', image: '/work/brand-alchemy/contact.webp' },
    ],
  },
  {
    slug: 'craft-shed',
    titleHtml: 'Craft<br><i>Shed</i>',
    shortName: 'Craft Shed',
    tag: 'Blinds & Outdoor Living · WordPress',
    num: '06 / 11',
    tagline: 'A lead-generation website for a New Zealand indoor and outdoor living company — bespoke blinds, shutters and louvre systems, with product collections, animated stats and free in-home quote requests.',
    client: 'Craft Shed',
    year: '2026',
    duration: '',
    role: 'Design, Development & SEO',
    industry: 'Blinds, Shutters & Outdoor Living',
    tags: ['WordPress', 'Custom Theme', 'Custom Post Types', 'Contact Form 7', 'Yoast SEO', 'Animated Counters', 'Responsive Design', 'LiteSpeed Cache'],
    metrics: ['17', '2', '4-step', 'Free'],
    mLabels: ['Products Online', 'Collections', 'Customer Journey', 'In-Home Quotes'],
    mChanges: ['Blinds, shutters & louvres', 'Indoor & outdoor, with filters', 'Consult, design, craft, install', 'Choose your nearest showroom'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://craftshed.nz',
    overviewHeading: ['Indoor and outdoor living, ', 'one', ' website'],
    overview: [
      'Craft Shed custom-makes and installs blinds, shutters and outdoor living systems for homes and businesses across New Zealand — from roller and zebra blinds to motorised louvre roofs, pergolas and carports. They needed one website that presented both ranges clearly and turned visitors into in-home quote requests.',
      'We designed and built a custom WordPress theme with a dedicated products system. Visitors switch between the Outdoor and Indoor collections and filter by category, then open product pages with image galleries, colour options and key warranty and finance highlights. The home page brings the brand to life with a full-width hero, animated stats and a four-step "how it works" journey.',
      'Every product page leads to a free quote: the contact page lets customers choose their nearest showroom, with office details and spam protection built in. Client reviews add trust, and Yoast SEO and LiteSpeed caching keep the site fast and visible in search — so Craft Shed is easy to find and easy to contact.',
    ],
    showcase: [
      { label: 'Home Page', text: 'Full-width hero, animated stats and clear quote calls to action', image: '/work/craft-shed/home.webp' },
      { label: 'Product Collections', text: 'Outdoor and indoor collections with category filters', image: '/work/craft-shed/products.webp' },
      { label: 'Product Detail', text: 'Gallery, colour options, warranty and finance highlights', image: '/work/craft-shed/product.webp' },
      { label: 'Contact & Quotes', text: 'Free quote requests with a choice of nearest showroom', image: '/work/craft-shed/contact.webp' },
    ],
  },
  {
    slug: 'earthy',
    titleHtml: 'Earthy<br><i>Eco Cleaning</i>',
    shortName: 'Earthy',
    tag: 'Eco Products · WordPress',
    num: '07 / 11',
    tagline: 'A product catalogue website for a New Zealand eco-friendly cleaning brand — plant-based cleaning products, compostables and washroom supplies, organised for both homes and commercial facilities.',
    client: 'Earthy',
    year: '2025',
    duration: '',
    role: 'Website Development · with Brand Alchemy',
    industry: 'Eco Cleaning Products',
    tags: ['WordPress', 'Custom Theme', 'Product Catalogue', 'Category Filters', 'Enquiry Workflow', 'Contact Form 7', 'Google Maps', 'SEO & Blog'],
    metrics: ['7', '3', '6', 'Eco'],
    mLabels: ['Product Categories', 'NZ Locations', 'Blog Articles', 'Brand Story'],
    mChanges: ['Cleaning to compostables', 'Auckland, Wellington & Christchurch', 'On sustainable cleaning', 'Tough on dirt, gentle on nature'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://earthy.co.nz',
    overviewHeading: ['Tough on dirt, ', 'gentle', ' on nature'],
    overview: [
      'Earthy supplies eco-friendly cleaning products across New Zealand — plant-based cleaning chemicals, compostable bags, heavy-duty wipes, toilet rolls and washroom supplies for homes and commercial facilities. Their website needed to make a sustainable message feel credible and make the full range easy to browse.',
      'We built a custom WordPress theme around the "Tough on Dirt. Gentle on Nature." brand and its leafy "Green Kiwi" mascot. The product catalogue is organised into seven categories with filter buttons, and each product page has an image gallery, a quantity selector and an "Enquire Now" button — ideal for trade and bulk orders.',
      'Subtle touches like drifting leaf animations carry the eco theme through the site. A blog on sustainable cleaning supports search visibility, and the contact page combines an enquiry form with an embedded map and details for Auckland, Wellington and Christchurch. The project was delivered in partnership with Brand Alchemy.',
    ],
    showcase: [
      { label: 'Home Page', text: 'The "Green Kiwi" brand story with a clear path to the shop', image: '/work/earthy/home.webp' },
      { label: 'Product Catalogue', text: 'Seven product categories with filter buttons', image: '/work/earthy/products.webp' },
      { label: 'Product Detail', text: 'Gallery, quantity selector and "Enquire Now"', image: '/work/earthy/product.webp' },
      { label: 'Contact', text: 'Enquiry form, embedded map and drifting leaf animation', image: '/work/earthy/contact.webp' },
    ],
  },
  {
    slug: 'unicorn-accounting',
    titleHtml: 'Unicorn<br><i>Accounting</i>',
    shortName: 'Unicorn Accounting',
    tag: 'Accounting Firm · WordPress',
    num: '08 / 11',
    tagline: 'A trust-building website for a firm of chartered accountants in Henderson, Auckland — designed as a React prototype, then built as a fully editable custom WordPress theme.',
    client: 'Unicorn Accounting Limited',
    year: '2026',
    duration: '',
    role: 'Design & Development · with Brand Alchemy',
    industry: 'Accounting & Tax',
    tags: ['WordPress', 'Custom Theme', 'React Prototype', 'Custom Post Types', 'Advanced Custom Fields', 'Contact Form 7', 'One-Click Setup', 'Responsive Design'],
    metrics: ['4', '100%', '3', '1-click'],
    mLabels: ['Service Pages', 'Editable in WP Admin', 'Custom Content Types', 'Theme Setup'],
    mChanges: ['Accounting, tax, cloud & startup', 'Every heading and paragraph', 'Services, team & certificates', 'Pages, menu & form on install'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://uca.co.nz',
    overviewHeading: ['Accounting, made ', 'approachable'],
    overview: [
      'Unicorn Accounting is a firm of chartered accountants and business advisors in Henderson, Auckland, helping small businesses with financial accounting, tax, cloud accounting and startup advice. Their website needed to build trust quickly and make it easy for business owners to get in touch.',
      'We designed the site first as a React prototype, then converted it into a custom WordPress theme with exactly the same look. Services, team members and certificates are their own content types, every heading and paragraph is editable in WP Admin, and a one-click installer sets up all the pages, content, menu and enquiry form when the theme is activated.',
      'Trust signals run throughout — the Google rating, Xero and MYOB partner badges and the team’s professional qualifications — alongside a clear fees page, a Contact Form 7 enquiry form and a Site Settings screen for phone numbers, address and social links. The project was delivered in partnership with Brand Alchemy.',
    ],
    showcase: [
      { label: 'Home Page', text: 'Google rating, Xero and MYOB badges and a clear call to talk', image: '/work/unicorn-accounting/home.webp' },
      { label: 'Services', text: 'Accounting, tax, cloud accounting and business startup', image: '/work/unicorn-accounting/services.webp' },
      { label: 'Contact', text: 'A friendly enquiry form with phone and office details', image: '/work/unicorn-accounting/contact.webp' },
    ],
  },
  {
    slug: 'the-concreator',
    titleHtml: 'The<br><i>Concreator</i>',
    shortName: 'The Concreator',
    tag: 'Architecture Studio · WordPress',
    num: '09 / 11',
    tagline: 'A portfolio website for an architecture and interior design studio — animated project showcases, service pages and video media, built on a custom WordPress theme.',
    client: 'The Concreator Architecture',
    year: '2025',
    duration: '',
    role: 'Website Development · with Brand Alchemy',
    industry: 'Architecture & Interiors',
    tags: ['WordPress', 'Custom Theme', 'Custom Post Types', 'GSAP', 'Three.js', 'Swiper', 'YouTube Media', 'Responsive Design'],
    metrics: ['5', '3', '2', 'Motion'],
    mLabels: ['Featured Projects', 'Service Areas', 'Studio Locations', 'Animation'],
    mChanges: ['Homes to commercial spaces', 'Interior, exterior & commercial', 'Contact details for both', 'GSAP & Three.js'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://concreators.co.in',
    overviewHeading: ['Architecture, ', 'in motion'],
    overview: [
      'The Concreator is an architecture and interior design studio designing homes, commercial complexes, religious institutions and resort spaces. As a design-led business, their website needed to let the work speak — with room for large imagery and a real sense of craft.',
      'We built a custom WordPress theme with a dedicated projects system, so every project has its own page and the portfolio grows as new work is completed. GSAP and Three.js add subtle motion throughout, and Swiper sliders present projects and imagery smoothly on every device.',
      'Service pages cover interior, exterior and commercial design, a News & Media section features interviews and YouTube videos, and contact details for both studio locations make it easy for new clients to get in touch. The project was delivered in partnership with Brand Alchemy.',
    ],
    showcase: [
      { label: 'Home Page', text: 'Bold, minimal typography that lets the studio speak', image: '/work/the-concreator/home.webp' },
      { label: 'Projects', text: 'A growing portfolio with a page for every project', image: '/work/the-concreator/projects.webp' },
      { label: 'Services', text: 'Interior, exterior and commercial design, shown through real work', image: '/work/the-concreator/services.webp' },
    ],
  },
  {
    slug: 'nz-motorcycle-movers',
    titleHtml: 'NZ Motorcycle<br><i>Movers</i>',
    shortName: 'NZ Motorcycle Movers',
    tag: 'Transport & Logistics · WordPress',
    num: '10 / 11',
    tagline: 'A website and online tracking system for a nationwide motorcycle transport company — quote requests, a delivery schedule and rego-based tracking so riders always know where their bike is.',
    client: 'NZ Motorcycle Movers',
    year: '2024',
    duration: '',
    role: 'Design & Development',
    industry: 'Transport & Logistics',
    tags: ['WordPress', 'Elementor', 'Rego Tracker', 'Delivery Schedule', 'Custom Post Types', 'FullCalendar', 'Contact Form 7', 'LiteSpeed Cache'],
    metrics: ['4', 'Rego', 'NZ-wide', '1 day'],
    mLabels: ['Depots', 'Online Tracking', 'Door-to-Door', 'Quote Response'],
    mChanges: ['Auckland, Wellington, Christchurch & Tauranga', 'Track by registration number', 'Bikes, quads & side-by-sides', 'Within one working day'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://nzmotorcyclemovers.co.nz',
    overviewHeading: ['Every bike, ', 'tracked', ' door to door'],
    overview: [
      'NZ Motorcycle Movers transports motorcycles, quads and side-by-sides door to door anywhere in New Zealand, with depots in Auckland, Wellington, Christchurch and Tauranga. Riders handing over their bike want reassurance — and they want to know where it is.',
      'We built the website on WordPress with Elementor, so the team can update pages themselves, presenting their nationwide coverage, services, FAQs, terms and real customer reviews. A detailed quote form captures the make and model, pickup and delivery locations up front, so the team can reply within one working day.',
      'The standout feature is online tracking: customers enter their vehicle registration number and see the status of their delivery instantly, without needing to call. Behind it is a custom delivery schedule system inside WordPress, using a calendar to organise pickups and deliveries.',
    ],
    showcase: [
      { label: 'Home Page', text: 'A bold, rider-focused hero with quote and tracking in the menu', image: '/work/nz-motorcycle-movers/home.webp' },
      { label: 'About', text: 'The company story, fleet and owner — built for trust', image: '/work/nz-motorcycle-movers/about.webp' },
      { label: 'Request a Quote', text: 'Make, model, pickup and delivery details alongside contact info', image: '/work/nz-motorcycle-movers/quote.webp' },
      { label: 'Online Tracking', text: 'Customers track their bike by registration number', image: '/work/nz-motorcycle-movers/tracking.webp' },
    ],
  },
  {
    slug: 'unique-movers',
    titleHtml: 'Unique<br><i>Movers</i>',
    shortName: 'Unique Movers',
    tag: 'Removals · Custom PHP',
    num: '11 / 11',
    tagline: 'A fast, custom-built website for an Auckland moving company — five service pages and a detailed online enquiry form that captures distance, dates and pickup and drop-off details up front.',
    client: 'Unique Movers',
    year: '2024',
    duration: '',
    role: 'Design & Development',
    industry: 'Removals & Relocation',
    tags: ['PHP', 'Bootstrap', 'jQuery', 'Swiper', 'Custom Enquiry Form', 'Google Analytics', 'Cloudflare', 'Responsive Design'],
    metrics: ['5', '6', '7 days', 'Fast'],
    mLabels: ['Service Pages', 'Pickup Time Slots', 'Enquiries Welcome', 'Lightweight Build'],
    mChanges: ['Local, home, corporate, packing & labour', 'Chosen in the enquiry form', '8am to 8pm, every day', 'Custom PHP on Cloudflare'],
    testQuote: '',
    testAv: '',
    testName: '',
    testRole: '',
    liveUrl: 'https://uniquemovers.co.nz',
    overviewHeading: ['Moving, made ', 'simple'],
    overview: [
      'Unique Movers helps households and businesses across Auckland move home and office — local moves, home relocation, corporate shifting, packing and extra labour, 7 days a week. Moving is stressful, so their website needed to load quickly, be easy to use and focus on bringing in enquiries.',
      'We built a custom PHP website with Bootstrap, keeping it lightweight without a heavy CMS. Each of the five services has its own page, and a hero slider, service highlights and clear "why choose us" points guide visitors towards getting in touch.',
      'The enquiry form captures everything the team needs to quote: approximate distance, pickup date and a two-hour time slot, and the pickup and drop-off locations. Google Analytics is set up to measure traffic, and Cloudflare keeps the site fast and protected.',
    ],
    showcase: [
      { label: 'Home Page', text: 'Hero slider with clear calls to get a quote, 7 days a week', image: '/work/unique-movers/home.webp' },
      { label: 'Services', text: 'Local moving, home relocation and corporate shifting at a glance', image: '/work/unique-movers/services.webp' },
      { label: 'Service Page', text: 'Each service with its own page and a "Book An Appointment" panel', image: '/work/unique-movers/service.webp' },
      { label: 'Contact', text: 'Phone numbers, email and the Takanini office', image: '/work/unique-movers/contact.webp' },
    ],
  },
];
