// Body content for each service detail page (/services/[slug]).
// Headings are [before, italic, after] so the emphasised word can be styled.
export type Heading = [string, string, string?];

export type ServiceContent = {
  cardDesc: string;
  cardTags: string[];
  overviewHeading: Heading;
  overview: string[];
  quote: string;
  featuresHeading: Heading;
  features: { title: string; desc: string }[];
  processHeading: Heading;
  process: { title: string; desc: string }[];
  tech: { name: string; role: string }[];
  related: string[];
  ctaHeading: Heading;
};

export const serviceContent: Record<string, ServiceContent> = {
  webdesign: {
    cardDesc: 'Strategy-led website design that makes a strong first impression and turns visitors into enquiries.',
    cardTags: ['Figma', 'UX Strategy', 'Responsive', 'SEO-ready'],
    overviewHeading: ['Where your ', 'brand', ' meets the web'],
    overview: [
      'Your website is often the first conversation a customer has with your business. We design sites that make that conversation easy — clear messaging, intuitive navigation and a look that reflects who you are.',
      'Every project starts with your goals and your audience, not a template. We plan the structure, write for search and design each page to guide visitors towards getting in touch, booking or buying.',
      'Designs go straight to our own developers, so what you approve is exactly what goes live — fast, accessible and easy for your team to update.',
    ],
    quote: "Good web design isn't decoration — it's the shortest path between your customer and what they came for.",
    featuresHeading: ['Everything your site ', 'needs to succeed'],
    features: [
      { title: 'Custom Page Design', desc: 'No templates. Every page is designed around your brand, your content and your goals.' },
      { title: 'Mobile-First Layouts', desc: 'Designed for phones first, then scaled up beautifully for tablets and desktops.' },
      { title: 'Conversion-Focused UX', desc: 'Clear calls to action, forms and journeys that turn visitors into leads and customers.' },
      { title: 'SEO-Ready Structure', desc: 'Clean headings, fast pages and search-friendly structure from day one.' },
      { title: 'Easy Content Editing', desc: 'A content management system your team can use to update pages without a developer.' },
      { title: 'Accessible by Design', desc: 'Readable type, strong colour contrast and keyboard-friendly navigation for every visitor.' },
    ],
    processHeading: ['Our web design ', 'process'],
    process: [
      { title: 'Discovery & Research', desc: 'Understanding your business, customers and competitors before any design starts.' },
      { title: 'Sitemap & Content Plan', desc: 'Planning pages, content and user journeys so visitors find what they need quickly.' },
      { title: 'Wireframes', desc: 'Low-detail layouts to agree on structure and priorities before visual design.' },
      { title: 'Visual Design', desc: 'Polished page designs that bring your brand to life, reviewed with you at each stage.' },
      { title: 'Build & QA', desc: 'Development and testing across devices and browsers by our own team.' },
      { title: 'Launch & Handoff', desc: 'Go-live, analytics setup, training and support after launch.' },
    ],
    tech: [
      { name: 'Figma', role: 'Design' },
      { name: 'Next.js', role: 'Framework' },
      { name: 'WordPress', role: 'CMS' },
      { name: 'Tailwind CSS', role: 'Styling' },
      { name: 'Google Analytics 4', role: 'Analytics' },
      { name: 'Search Console', role: 'SEO' },
      { name: 'Lighthouse', role: 'Performance' },
      { name: 'Vercel', role: 'Hosting' },
    ],
    related: ['ui', 'responsive', 'seo'],
    ctaHeading: ['Ready to design your', 'new website?'],
  },

  ui: {
    cardDesc: 'Research-backed UX and polished interfaces for web apps, software and mobile products.',
    cardTags: ['User Research', 'Prototyping', 'Design Systems', 'Figma'],
    overviewHeading: ['Designing for the ', 'people', ' who use it'],
    overview: [
      "Great software fails if people can't work out how to use it. Our UI/UX design makes complex products feel simple — whether it's a customer-facing app, an internal dashboard or a SaaS platform.",
      'We start with the people who will use your product — their goals, frustrations and context — then map user flows, test prototypes and refine until every screen earns its place.',
      'The result is a design system your developers can build from directly: consistent components, clear interaction states and documentation that keeps your product coherent as it grows.',
    ],
    quote: 'The best interface is the one your users never have to think about.',
    featuresHeading: ['Everything your product ', 'needs to be usable'],
    features: [
      { title: 'User Research', desc: 'Interviews, analytics and competitor reviews to understand what your users really need.' },
      { title: 'User Flows & Journeys', desc: 'Mapping every path through your product so tasks take as few steps as possible.' },
      { title: 'Wireframes & Prototypes', desc: 'Clickable prototypes to test ideas with real users before any code is written.' },
      { title: 'Visual UI Design', desc: 'Clean, modern interfaces that reflect your brand and make actions obvious.' },
      { title: 'Design Systems', desc: 'Reusable components, colours and type rules that keep your product consistent.' },
      { title: 'Usability Testing', desc: 'Watching real people use the design and fixing what slows them down.' },
    ],
    processHeading: ['Our UX ', 'process'],
    process: [
      { title: 'Discover', desc: 'Workshops, research and analytics to understand users and business goals.' },
      { title: 'Define', desc: 'User flows and information architecture that shape the whole product.' },
      { title: 'Wireframe', desc: 'Fast, low-detail layouts to explore and agree on structure.' },
      { title: 'Prototype & Test', desc: 'Interactive prototypes tested with real users, then refined.' },
      { title: 'Visual Design', desc: 'High-fidelity screens, interaction states and motion details.' },
      { title: 'Developer Handoff', desc: 'Specs, components and documentation ready for development.' },
    ],
    tech: [
      { name: 'Figma', role: 'UI Design' },
      { name: 'FigJam', role: 'Workshops & Flows' },
      { name: 'Framer', role: 'Prototyping' },
      { name: 'Adobe Illustrator', role: 'Icons & Graphics' },
      { name: 'Lottie / Rive', role: 'Micro-interactions' },
      { name: 'Storybook', role: 'Component Library' },
      { name: 'React', role: 'Front-end Build' },
      { name: 'Google Analytics 4', role: 'Behaviour Data' },
    ],
    related: ['webdev', 'mobile', 'webdesign'],
    ctaHeading: ['Ready to make your product', 'easier to use?'],
  },

  branding: {
    cardDesc: 'Complete identity systems that keep your business consistent across every channel.',
    cardTags: ['Brand Strategy', 'Visual Identity', 'Guidelines', 'Print'],
    overviewHeading: ['A brand that ', 'works', ' everywhere'],
    overview: [
      'Strong brands are recognised before anyone reads a word. We build complete identity systems — logo, colour, typography and tone of voice — so your business looks and sounds the same on every channel.',
      'Because we are a software and web company, we design identities that work where they actually live: websites, apps, dashboards, email signatures and social media, as well as print.',
      'You receive clear brand guidelines and production-ready files, so your team, printers and partners can apply the brand correctly without guesswork.',
    ],
    quote: 'Consistency is what turns a logo into a brand.',
    featuresHeading: ['Everything your brand ', 'needs to stand out'],
    features: [
      { title: 'Brand Strategy', desc: 'Positioning, audience and personality defined before any visuals are designed.' },
      { title: 'Visual Identity', desc: 'Logo, colour palette and typography that work together as one system.' },
      { title: 'Brand Guidelines', desc: 'A clear guide showing how to use your brand correctly, everywhere.' },
      { title: 'Digital Brand Assets', desc: 'Social templates, app icons, email signatures and presentation templates.' },
      { title: 'Print Collateral', desc: 'Business cards, letterheads, brochures, flyers and invoices.' },
      { title: 'Brand Refresh', desc: 'Modernising an existing brand without losing the recognition you have built.' },
    ],
    processHeading: ['Our branding ', 'process'],
    process: [
      { title: 'Discovery Workshop', desc: 'Exploring your story, values, customers and ambitions together.' },
      { title: 'Research & Positioning', desc: 'Reviewing your market and competitors to find your distinct position.' },
      { title: 'Concept Development', desc: 'Several creative directions presented with clear reasoning.' },
      { title: 'Refinement', desc: 'Developing the chosen direction based on your feedback.' },
      { title: 'Identity System', desc: 'Extending the brand across colour, type, imagery and templates.' },
      { title: 'Guidelines & Delivery', desc: 'Brand guidelines and every file your team will need.' },
    ],
    tech: [
      { name: 'Adobe Illustrator', role: 'Vector Design' },
      { name: 'Adobe Photoshop', role: 'Image Editing' },
      { name: 'Adobe InDesign', role: 'Print Layout' },
      { name: 'Figma', role: 'Digital Assets' },
      { name: 'Canva', role: 'Team Templates' },
      { name: 'Lottie / Rive', role: 'Animated Logos' },
      { name: 'Google Fonts', role: 'Web Typography' },
      { name: 'PDF / SVG', role: 'Delivery Formats' },
    ],
    related: ['logo', 'webdesign', 'ui'],
    ctaHeading: ['Ready to build a brand', 'people remember?'],
  },

  logo: {
    cardDesc: 'Distinctive, versatile logos that look sharp everywhere, from app icons to signage.',
    cardTags: ['Logo Concepts', 'Icon Design', 'Typography', 'All Formats'],
    overviewHeading: ['First impressions, ', 'designed'],
    overview: [
      'Your logo is the most-seen piece of your brand. We design marks that are simple enough to remember, distinctive enough to stand out and flexible enough to work everywhere.',
      'We explore several directions based on your business, audience and competitors, then refine your chosen concept until every curve and letterform is right.',
      'You get a complete logo suite — primary, stacked and icon versions in colour, black and white — in every file format you need for web, apps and print.',
    ],
    quote: 'A great logo is simple enough to sketch from memory.',
    featuresHeading: ['Everything your logo ', 'needs to last'],
    features: [
      { title: 'Multiple Concepts', desc: 'Several distinct design directions to choose from, each with clear reasoning.' },
      { title: 'Refinement Rounds', desc: 'We polish your chosen concept together until it is exactly right.' },
      { title: 'Responsive Logo Suite', desc: 'Full, stacked and icon versions that work at any size.' },
      { title: 'All File Formats', desc: 'SVG, PNG, PDF and EPS files ready for screen and print.' },
      { title: 'Colour & Mono Versions', desc: 'Versions for light, dark and single-colour backgrounds.' },
      { title: 'Favicon & App Icons', desc: 'Your mark prepared for browser tabs, app stores and social profiles.' },
    ],
    processHeading: ['Our logo design ', 'process'],
    process: [
      { title: 'Brief & Research', desc: 'Learning about your business, audience and competitors.' },
      { title: 'Sketching', desc: 'Exploring a wide range of ideas quickly on paper.' },
      { title: 'Digital Concepts', desc: 'Developing the strongest ideas into refined digital concepts.' },
      { title: 'Presentation', desc: 'Showing each concept in real-world settings so you can choose with confidence.' },
      { title: 'Refinement', desc: 'Fine-tuning shapes, spacing, colour and type.' },
      { title: 'Final Files', desc: 'Delivering the full logo suite and usage notes.' },
    ],
    tech: [
      { name: 'Adobe Illustrator', role: 'Vector Design' },
      { name: 'Adobe Photoshop', role: 'Mockups' },
      { name: 'Figma', role: 'Presentation' },
      { name: 'Procreate', role: 'Sketching' },
      { name: 'SVG', role: 'Web Format' },
      { name: 'PNG', role: 'Digital Format' },
      { name: 'PDF / EPS', role: 'Print Formats' },
      { name: 'ICO', role: 'Favicons' },
    ],
    related: ['branding', 'webdesign', 'ui'],
    ctaHeading: ['Ready for a logo', 'that lasts?'],
  },

  responsive: {
    cardDesc: 'Websites and web apps that adapt perfectly to every phone, tablet and desktop.',
    cardTags: ['Mobile-first', 'Cross-device', 'Fast Loading', 'Mobile SEO'],
    overviewHeading: ['One site, ', 'every', ' screen'],
    overview: [
      'Most of your visitors arrive on a phone. If your site is hard to read or use on a small screen, they leave — and Google ranks you lower for it.',
      'We design and build mobile-first, then scale layouts up for tablets and large displays, so content, navigation and forms work beautifully on every device.',
      "Already have a website that doesn't work well on mobile? We can rebuild or retrofit it with responsive layouts, faster loading and touch-friendly interactions.",
    ],
    quote: "Responsive isn't a feature anymore — it's the baseline your customers expect.",
    featuresHeading: ['Everything your site ', 'needs on every device'],
    features: [
      { title: 'Mobile-First Design', desc: 'Layouts designed for small screens first, so nothing important gets lost.' },
      { title: 'Flexible Layouts', desc: 'Fluid grids and components that adapt smoothly to any screen size.' },
      { title: 'Touch-Friendly UI', desc: 'Buttons, menus and forms sized and spaced for fingers, not just mice.' },
      { title: 'Optimised Images', desc: 'Images served at the right size for each device to keep pages fast.' },
      { title: 'Cross-Browser Testing', desc: 'Checked on Chrome, Safari, Firefox and Edge across real devices.' },
      { title: 'Mobile SEO', desc: "Built for Google's mobile-first indexing, so mobile users can find you." },
    ],
    processHeading: ['Our responsive ', 'process'],
    process: [
      { title: 'Device & Audience Audit', desc: 'Understanding which devices and browsers your customers use.' },
      { title: 'Mobile-First Wireframes', desc: 'Planning the small-screen experience before scaling up.' },
      { title: 'Breakpoint Design', desc: 'Designing how each layout adapts across phone, tablet and desktop.' },
      { title: 'Responsive Build', desc: 'Flexible, performance-focused code that adapts to any screen.' },
      { title: 'Device Testing', desc: 'Testing on real phones, tablets and desktops before launch.' },
      { title: 'Launch & Monitor', desc: 'Tracking speed and mobile usability after go-live.' },
    ],
    tech: [
      { name: 'CSS Grid & Flexbox', role: 'Layout' },
      { name: 'Tailwind CSS', role: 'Styling' },
      { name: 'Next.js', role: 'Framework' },
      { name: 'Figma', role: 'Design' },
      { name: 'BrowserStack', role: 'Device Testing' },
      { name: 'Lighthouse', role: 'Performance' },
      { name: 'PageSpeed Insights', role: 'Mobile Speed' },
      { name: 'Search Console', role: 'Mobile Usability' },
    ],
    related: ['webdesign', 'webdev', 'seo'],
    ctaHeading: ['Ready for a site that works', 'on every screen?'],
  },

  webdev: {
    cardDesc: 'Bespoke web applications, portals, dashboards and APIs built around how your business works.',
    cardTags: ['React / Next.js', 'Node.js', 'PostgreSQL', 'APIs'],
    overviewHeading: ['Software built around ', 'your', ' business'],
    overview: [
      'Off-the-shelf software rarely fits perfectly. We build custom web applications that match the way you work — from customer portals and booking systems to internal dashboards and SaaS products.',
      'Our team handles the full stack: front-end interfaces, back-end logic, databases, APIs and integrations with the tools you already use, such as accounting, payments and CRM systems.',
      'We write clean, tested, well-documented code and deploy it on reliable cloud infrastructure, so your software is secure today and easy to extend tomorrow. You own the code outright.',
    ],
    quote: "The right software doesn't change how you work — it removes what slows you down.",
    featuresHeading: ['Everything your software ', 'needs to scale'],
    features: [
      { title: 'Web Applications', desc: 'Custom, browser-based software built for your exact processes.' },
      { title: 'Customer & Staff Portals', desc: 'Secure logins where customers or staff can manage accounts, bookings and data.' },
      { title: 'Dashboards & Reporting', desc: 'Real-time views of the numbers that matter to your business.' },
      { title: 'APIs & Integrations', desc: 'Connecting your systems so data flows automatically, without double entry.' },
      { title: 'Cloud Hosting & DevOps', desc: 'Reliable deployment, automated backups and monitoring on modern cloud platforms.' },
      { title: 'Security & Maintenance', desc: 'Secure authentication, regular updates and ongoing support after launch.' },
    ],
    processHeading: ['Our development ', 'process'],
    process: [
      { title: 'Discovery & Scoping', desc: 'Defining requirements, users and success measures before we write code.' },
      { title: 'Architecture & Planning', desc: 'Choosing the right technology and planning a system that can grow.' },
      { title: 'UX & Interface Design', desc: 'Designing screens and workflows your users will find easy.' },
      { title: 'Agile Development', desc: 'Building in short sprints with regular demos, so you see progress every step.' },
      { title: 'Testing & QA', desc: 'Automated and manual testing for reliability, security and performance.' },
      { title: 'Deployment & Support', desc: 'Launch, documentation, training and ongoing improvements.' },
    ],
    tech: [
      { name: 'React / Next.js', role: 'Front-end' },
      { name: 'TypeScript', role: 'Language' },
      { name: 'Node.js', role: 'Back-end' },
      { name: 'PostgreSQL', role: 'Database' },
      { name: 'GraphQL / REST', role: 'APIs' },
      { name: 'Prisma', role: 'Data Layer' },
      { name: 'AWS', role: 'Cloud' },
      { name: 'Vercel', role: 'Hosting' },
    ],
    related: ['ui', 'mobile', 'ecommerce'],
    ctaHeading: ['Ready to build your', 'custom software?'],
  },

  mobile: {
    cardDesc: 'iOS and Android apps that feel fast and natural, built from one cross-platform codebase.',
    cardTags: ['iOS', 'Android', 'React Native', 'App Store'],
    overviewHeading: ['Your business, in your ', "customers'", ' pocket'],
    overview: [
      'A well-built app keeps your customers connected to your business — booking, ordering, tracking or managing their account wherever they are.',
      'We build with React Native, which means one codebase for both iOS and Android. You get native-feeling performance and a consistent experience on both platforms, with less time and effort than two separate apps.',
      'We take care of the whole journey: UX design, development, back-end and API integration, App Store and Google Play submission, and updates after launch.',
    ],
    quote: "An app earns its place on the home screen by being genuinely useful every time it's opened.",
    featuresHeading: ['Everything your app ', 'needs to succeed'],
    features: [
      { title: 'iOS & Android', desc: 'One cross-platform app that runs smoothly on iPhone and Android devices.' },
      { title: 'Native-Feel UX', desc: 'Gestures, navigation and animations that feel at home on each platform.' },
      { title: 'Back-end & APIs', desc: 'Secure servers and databases that power your app and sync data in real time.' },
      { title: 'Push Notifications', desc: 'Timely updates and reminders that bring users back.' },
      { title: 'Offline Support', desc: 'Key features keep working even with a weak or no connection.' },
      { title: 'App Store Launch', desc: 'We handle App Store and Google Play submission, listings and approvals.' },
    ],
    processHeading: ['Our app development ', 'process'],
    process: [
      { title: 'Discovery & Strategy', desc: 'Defining your users, core features and success measures.' },
      { title: 'UX & Prototyping', desc: 'Mapping flows and testing a clickable prototype before development.' },
      { title: 'UI Design', desc: 'Polished screens designed for both iOS and Android.' },
      { title: 'Development Sprints', desc: 'Building in short cycles with test builds on your own phone.' },
      { title: 'Real-Device Testing', desc: 'Testing across phones, screen sizes and operating system versions.' },
      { title: 'Store Launch & Updates', desc: 'Publishing to the stores, then monitoring and improving.' },
    ],
    tech: [
      { name: 'React Native', role: 'Cross-platform' },
      { name: 'Expo', role: 'Build & Deploy' },
      { name: 'TypeScript', role: 'Language' },
      { name: 'Node.js', role: 'Back-end' },
      { name: 'Supabase', role: 'Data & Auth' },
      { name: 'Firebase', role: 'Push Notifications' },
      { name: 'App Store Connect', role: 'iOS Release' },
      { name: 'Google Play Console', role: 'Android Release' },
    ],
    related: ['webdev', 'ui', 'ecommerce'],
    ctaHeading: ['Ready to build', 'your app?'],
  },

  ecommerce: {
    cardDesc: 'Online stores on Shopify, WooCommerce or custom platforms, built to convert and easy to manage.',
    cardTags: ['Shopify', 'WooCommerce', 'Custom', 'Payments'],
    overviewHeading: ['Online stores that ', 'sell'],
    overview: [
      'Your online store has to do more than display products. It needs to build trust, make finding the right item effortless and remove every bit of friction from checkout.',
      "We build on Shopify and WooCommerce for most businesses, and develop custom e-commerce platforms when you need something they can't do — complex pricing, B2B ordering or deep system integrations.",
      'Every store is set up with secure payments, shipping and tax rules, inventory management and analytics, so you can start selling locally or internationally from day one.',
    ],
    quote: 'Every extra click at checkout is a customer you might lose.',
    featuresHeading: ['Everything your store ', 'needs to sell'],
    features: [
      { title: 'Custom Store Design', desc: 'A store that reflects your brand and makes products easy to find.' },
      { title: 'Shopify & WooCommerce', desc: 'Proven platforms, customised to fit your products and processes.' },
      { title: 'Secure Payments', desc: 'Card, digital wallet and buy-now-pay-later options with a fast checkout.' },
      { title: 'Product & Inventory', desc: 'Simple tools to manage products, variants, stock and orders.' },
      { title: 'Shipping & Tax Setup', desc: 'Shipping zones, rates and tax rules configured for where you sell.' },
      { title: 'Store Migration', desc: 'Moving from another platform without losing products, customers or search rankings.' },
    ],
    processHeading: ['Our e-commerce ', 'process'],
    process: [
      { title: 'Discovery & Planning', desc: 'Understanding your products, customers and operations.' },
      { title: 'Store UX & Design', desc: 'Designing product pages, navigation and checkout for conversion.' },
      { title: 'Platform Setup & Build', desc: 'Configuring and customising the right platform for you.' },
      { title: 'Products & Payments', desc: 'Loading products and setting up payments, shipping and tax.' },
      { title: 'Testing & Launch', desc: 'Test orders on every device before opening the doors.' },
      { title: 'Growth & Optimisation', desc: 'Improving conversion, speed and search visibility after launch.' },
    ],
    tech: [
      { name: 'Shopify', role: 'Platform' },
      { name: 'WooCommerce', role: 'Platform' },
      { name: 'Next.js', role: 'Headless Store' },
      { name: 'Stripe', role: 'Payments' },
      { name: 'PayPal', role: 'Payments' },
      { name: 'Xero', role: 'Accounting Sync' },
      { name: 'Google Analytics 4', role: 'Analytics' },
      { name: 'Google Merchant Center', role: 'Product Listings' },
    ],
    related: ['webdev', 'seo', 'webdesign'],
    ctaHeading: ['Ready to grow', 'your online sales?'],
  },

  seo: {
    cardDesc: 'Technical SEO, on-page optimisation, local search and fast pages, so customers find you on Google.',
    cardTags: ['Technical SEO', 'Local SEO', 'Core Web Vitals', 'Analytics'],
    overviewHeading: ['Be found by the ', 'right', ' customers'],
    overview: [
      "The best website in the world won't help if nobody finds it. Our SEO service puts your business in front of people actively searching for what you offer — in New Zealand and overseas.",
      'We start with a full technical audit and keyword research, then fix what is holding you back: slow pages, crawl errors, missing metadata, thin content and weak site structure.',
      "From there we optimise your pages, set up Google Business Profile and local search, and track rankings, traffic and enquiries so you can see exactly what's working.",
    ],
    quote: 'SEO is a long game — and a technically sound website is where every win starts.',
    featuresHeading: ['Everything you need ', 'to rank'],
    features: [
      { title: 'Technical SEO Audit', desc: 'A full check of speed, indexing, crawl errors and site structure.' },
      { title: 'Keyword Research', desc: 'Finding the searches your customers actually use, and the ones you can win.' },
      { title: 'On-Page Optimisation', desc: 'Titles, descriptions, headings, content and internal links tuned for search.' },
      { title: 'Local SEO', desc: 'Google Business Profile, local listings and location pages to win nearby searches.' },
      { title: 'Core Web Vitals', desc: 'Faster loading and smoother pages, which Google rewards.' },
      { title: 'Analytics & Reporting', desc: 'Google Analytics and Search Console set up so you can track real results.' },
    ],
    processHeading: ['Our SEO ', 'process'],
    process: [
      { title: 'Audit', desc: 'Reviewing your site, rankings, traffic and competitors.' },
      { title: 'Keyword & Competitor Research', desc: 'Identifying the searches with the best opportunity for you.' },
      { title: 'Technical Fixes', desc: 'Resolving speed, indexing, structure and structured-data issues.' },
      { title: 'On-Page Optimisation', desc: 'Improving page content, metadata and internal linking.' },
      { title: 'Content & Local SEO', desc: 'New content and local listings that build visibility over time.' },
      { title: 'Track & Improve', desc: 'Measuring rankings, traffic and enquiries, then refining.' },
    ],
    tech: [
      { name: 'Search Console', role: 'Indexing' },
      { name: 'Google Analytics 4', role: 'Analytics' },
      { name: 'Google Business Profile', role: 'Local SEO' },
      { name: 'Tag Manager', role: 'Tracking' },
      { name: 'PageSpeed Insights', role: 'Performance' },
      { name: 'Lighthouse', role: 'Audits' },
      { name: 'Schema.org', role: 'Structured Data' },
      { name: 'XML Sitemaps', role: 'Crawling' },
    ],
    related: ['webdesign', 'ecommerce', 'responsive'],
    ctaHeading: ['Ready to get found', 'on Google?'],
  },

  corporate: {
    cardDesc: 'Professional, high-trust websites for established organisations, with easy content management.',
    cardTags: ['Enterprise CMS', 'Accessibility', 'Security', 'Integrations'],
    overviewHeading: ['Websites that build ', 'trust'],
    overview: [
      'For established organisations, your website is a key source of credibility for customers, investors, partners and future staff. It needs to be clear, professional and always up to date.',
      'We design and build corporate websites with well-planned structure, role-based editing and approval workflows, so the right people can update the right pages safely.',
      'Security, accessibility and performance are built in from the start, with hosting, backups and ongoing maintenance available so your site stays reliable long after launch.',
    ],
    quote: 'A corporate website should make it easy to say yes to working with you.',
    featuresHeading: ['Everything your organisation ', 'needs online'],
    features: [
      { title: 'Information Architecture', desc: 'Clear structure for large amounts of content, so every audience finds its way.' },
      { title: 'CMS & Workflows', desc: 'Role-based editing and approvals so teams can publish safely.' },
      { title: 'Accessibility', desc: 'Designed and built to WCAG 2.1 guidelines for every visitor.' },
      { title: 'Security & Backups', desc: 'Hardened hosting, SSL, regular updates and automated backups.' },
      { title: 'Integrations', desc: 'Connections to your CRM, recruitment, newsletter and other business systems.' },
      { title: 'Ongoing Maintenance', desc: 'Updates, monitoring and support plans after launch.' },
    ],
    processHeading: ['Our corporate website ', 'process'],
    process: [
      { title: 'Stakeholder Workshops', desc: 'Aligning teams on goals, audiences and requirements.' },
      { title: 'Content & Structure', desc: 'Planning sitemaps, page types and content ownership.' },
      { title: 'Design System', desc: 'A flexible, on-brand set of page templates and components.' },
      { title: 'CMS Build', desc: 'Developing the site and editing tools your team will use.' },
      { title: 'Content Migration', desc: 'Moving existing content across, with redirects to protect search rankings.' },
      { title: 'Launch & Training', desc: 'Go-live, editor training and documentation.' },
    ],
    tech: [
      { name: 'WordPress', role: 'CMS' },
      { name: 'Next.js', role: 'Front-end' },
      { name: 'Sanity', role: 'Headless CMS' },
      { name: 'Contentful', role: 'Headless CMS' },
      { name: 'Cloudflare', role: 'Security & CDN' },
      { name: 'Vercel', role: 'Hosting' },
      { name: 'Google Analytics 4', role: 'Analytics' },
      { name: 'Search Console', role: 'SEO' },
    ],
    related: ['webdesign', 'webdev', 'seo'],
    ctaHeading: ['Ready for a website that', 'builds trust?'],
  },
};

// Used for services added in WordPress that have no body content in code yet.
export const defaultServiceContent: ServiceContent = {
  ...serviceContent.webdev,
  related: ['webdesign', 'webdev', 'seo'],
  ctaHeading: ['Ready to start', 'your project?'],
};
